"""NVIDIA NeMo Switchyard as a routing policy.

Switchyard is normally deployed as an OpenAI-compatible *proxy* that both routes
and executes. That does not fit here, because Turnout's providers are local
CLI subprocesses with subscription auth rather than HTTP endpoints with API keys.

So we use its `/v1/decision` endpoint instead, which answers "which target should
serve this?" without making the answer call. Switchyard becomes one interchangeable
implementation of the Router protocol, and Turnout keeps execution.

Wire contract, read off the v0.2.0 source (crates/switchyard-server/src/lib.rs):

    POST /v1/decision
    {"input_format": "openai_chat", "request": {<an OpenAI chat body>}}

    -> {"selected":  {"target": str, "model": str,
                      "llm_client": {"format": str, "base_url": str},
                      "extra_body": {}},
        "fallbacks": [ ...same shape... ],
        "response":  {...}   # only present when the route produced a preview
       }

`input_format` is required -- the struct is `deny_unknown_fields` with no default.
The inbound `model` names a *route id*, not a model, and `selected.model` is the
target's configured id, which the generated config sets to the Turnout target id.
"""

from __future__ import annotations

import httpx

from ..domain import Candidate, Decision, RoutingContext, RoutingRequest, now_ms
from ..switchyard_config import ROUTE_CLASSIFIER, target_from_switchyard_name
from .base import BaseRouter


class SwitchyardRouter(BaseRouter):
    name = "switchyard"
    version = "0.2.0"

    def __init__(
        self, base_url: str = "http://127.0.0.1:4000",
        route: str = ROUTE_CLASSIFIER, fallback_target: str = "",
        timeout_s: float = 60.0, name: str | None = None,
    ):
        # One instance per configured route, so the name has to be per-instance:
        # leaving it on the class made every Switchyard route indistinguishable
        # in the database and merged them in the per-router analytics.
        if name:
            self.name = name
        self.route = route
        self.base_url = base_url.rstrip("/")
        self.fallback_target = fallback_target
        self.timeout_s = timeout_s

    async def health(self) -> tuple[bool, str]:
        try:
            async with httpx.AsyncClient(timeout=5.0) as c:
                r = await c.get(f"{self.base_url}/health")
            return r.status_code == 200, f"HTTP {r.status_code} at {self.base_url}"
        except Exception as e:  # noqa: BLE001
            return False, f"unreachable at {self.base_url}: {type(e).__name__}"

    async def decide(self, req: RoutingRequest, ctx: RoutingContext) -> Decision:
        t0 = now_ms()
        eligible = ctx.catalog.eligible(req.constraints)
        if not eligible:
            raise RuntimeError("no eligible targets for this request")

        payload = {
            "input_format": "openai_chat",
            "request": {
                "model": self.route,
                "messages": [m.to_dict() for m in req.messages],
                # Switchyard keys session affinity off the conversation itself;
                # passing our session id through `user` keeps its notion of a
                # session aligned with Turnout's.
                "user": req.session_id,
            },
        }
        async with httpx.AsyncClient(timeout=self.timeout_s) as client:
            resp = await client.post(f"{self.base_url}/v1/decision", json=payload)
        if resp.status_code != 200:
            raise RuntimeError(f"switchyard /v1/decision returned {resp.status_code}: {resp.text[:300]}")
        body = resp.json()

        def resolve(entry: dict) -> str | None:
            # `model` is the target's configured id, which the generated config
            # sets to the Turnout target id. Fall back to un-mangling the TOML
            # table name for configs that were not generated by Turnout.
            model = entry.get("model")
            if model and ctx.catalog.get(model):
                return model
            return target_from_switchyard_name(entry.get("target", ""), ctx.catalog.targets)

        selected = resolve(body.get("selected") or {})
        if selected is None:
            raise RuntimeError(
                f"switchyard selected '{(body.get('selected') or {}).get('target')}', "
                "which is not a known Turnout target -- regenerate the Switchyard config"
            )

        fallbacks = [t for t in (resolve(f) for f in body.get("fallbacks") or []) if t]
        eligible_ids = {t.id for t in eligible}

        # Switchyard has no view of Turnout's constraints, so a target it
        # picks may be ineligible here. Honour Turnout's constraints: they are
        # the user's, and a router does not get to overrule them.
        if selected not in eligible_ids:
            replacement = next((f for f in fallbacks if f in eligible_ids), None)
            if replacement is None:
                raise RuntimeError(
                    f"switchyard chose '{selected}', excluded by this request's constraints, "
                    "and offered no eligible fallback"
                )
            note = f" (switchyard chose `{selected}`, excluded by constraints)"
            selected = replacement
        else:
            note = ""

        ordered = [selected] + [f for f in fallbacks if f != selected and f in eligible_ids]
        candidates = [
            Candidate(tid, round(1.0 - i * 0.1, 3),
                      ["switchyard selection" if i == 0 else f"switchyard fallback #{i}"])
            for i, tid in enumerate(ordered)
        ]

        preview = body.get("response")
        rationale = (
            f"Switchyard route `{self.route}` selected `{selected}`{note}. "
            f"Fallback order: {', '.join(fallbacks) or 'none'}."
        )
        if preview:
            rationale += " Route returned a preview response."

        d = self._decision(
            req, ctx, target_id=selected, rationale=rationale,
            candidates=candidates, started_ms=t0,
            # Switchyard does not expose a score or margin, so claiming a
            # calibrated confidence here would be an invention.
            confidence=None, raw=body,
        )
        d.fallback_order = [c.target_id for c in candidates[1:]]
        return d
