"""Generate a Switchyard server config from the Turnout target catalog.

The interesting move here is where Switchyard's `llm_clients` point: back at
Turnout itself, on /v1/chat/completions.

That closes the loop cleanly. Switchyard's job in this system is to *decide*,
and Turnout executes -- but some Switchyard routes (the LLM classifier, the
advisor) need to make a real model call of their own to reach a decision. By
making Turnout Switchyard's backend, those calls run on the same CLI
providers as everything else, with no API keys and no second execution path.

There is no recursion risk: a classifier call arrives with `model` set to a
concrete target id, which Turnout treats as a pin and executes directly
without consulting a router.
"""

from __future__ import annotations

from pathlib import Path

from .config import TurnoutConfig
from .domain import Target

# Route ids double as the `model` string a client sends to select a route.
ROUTE_RANDOM = "switchyard/random"
ROUTE_CLASSIFIER = "switchyard/classifier"
ROUTE_PASSTHROUGH = "switchyard/passthrough"
ROUTE_STAGE = "switchyard/stage"

# TOML table keys are constrained; Turnout ids are not. Keep the mapping trivial
# and reversible rather than clever, because the decision response echoes the
# target *name* back and we have to map it home.
def _key(target_id: str) -> str:
    return target_id.replace("-", "_").replace(".", "_")


def _unkey(name: str, targets: list[Target]) -> str | None:
    for t in targets:
        if _key(t.id) == name:
            return t.id
    return None


def target_from_switchyard_name(name: str, targets: list[Target]) -> str | None:
    return _unkey(name, targets)


def pick_tiers(targets: list[Target]) -> tuple[Target, Target, Target]:
    """Choose (weak, strong, classifier) from the catalog.

    The classifier should be cheap and fast -- it runs on every new session and
    its own latency is added to every routed request.
    """
    by_quality = sorted(targets, key=lambda t: (t.quality_tier, -t.cost_tier))
    weak = by_quality[0]
    strong = by_quality[-1]
    classifier = min(targets, key=lambda t: (t.speed_tier, t.cost_tier))
    return weak, strong, classifier


def generate(cfg: TurnoutConfig, turnout_base_url: str | None = None) -> str:
    targets = [t for t in cfg.targets.targets if t.enabled]
    if not targets:
        raise ValueError("no enabled targets; cannot generate a Switchyard config")

    base_url = turnout_base_url or f"http://{cfg.host}:{cfg.port}/v1"
    weak, strong, classifier = pick_tiers(targets)
    default = cfg.targets.get(cfg.default_target) or targets[0]

    lines: list[str] = [
        "# GENERATED by turnout.switchyard_config -- do not edit by hand.",
        "# Regenerate with:  turnout switchyard write-config",
        "#",
        "# Every llm_client points back at Turnout, so Switchyard's own",
        "# routing-time model calls run on the same CLI providers as everything",
        "# else. No API keys are needed anywhere in this file.",
        "",
        "schema_version = 1",
        "",
        "[llm_clients.turnout]",
        'format = "openai_chat"',
        f'base_url = "{base_url}"',
        "",
        "# ---------------------------------------------------------------- targets",
    ]

    for t in targets:
        lines += [
            "",
            f"# {t.label} -- quality {t.quality_tier}, cost {t.cost_tier}, speed {t.speed_tier}",
            f"[targets.{_key(t.id)}]",
            f'id = "{t.id}"',
            'llm_client = "turnout"',
            # Switchyard merges extra_body into the request it sends here, which
            # is the only way to tell its routing-time calls (an llm_classifier
            # judging a task) apart from a real user request. Without it those
            # internal calls land in the history as if the user had typed them.
            "extra_body = { turnout_internal = true }",
        ]

    all_keys = ", ".join(f'"{_key(t.id)}"' for t in targets)
    lines += [
        "",
        "# ----------------------------------------------------------------- routes",
        "#",
        "# A route's `id` is the model string a client sends to select it, so",
        "# Turnout asks for a decision by naming one of these.",
        "",
        "# Uniform random over every target. Useful as an exploration policy:",
        "# it produces the unbiased data a learned router needs.",
        "[routes.random]",
        f'id = "{ROUTE_RANDOM}"',
        'type = "random"',
        f"targets = [{all_keys}]",
        "",
        "# Always the Turnout default. The control condition.",
        "[routes.passthrough]",
        f'id = "{ROUTE_PASSTHROUGH}"',
        'type = "passthrough"',
        f'target = "{_key(default.id)}"',
        "",
        "# Switchyard's real routing algorithm: a cheap model judges how hard the",
        "# task is, then the request goes to the strong or the weak target.",
        "[routes.classifier]",
        f'id = "{ROUTE_CLASSIFIER}"',
        'type = "llm_classifier"',
        'mode = "capability"',
        f'classifier_target = "{_key(classifier.id)}"',
        f'strong_target = "{_key(strong.id)}"',
        f'weak_target = "{_key(weak.id)}"',
        "base_threshold = 0.5",
        'classify_trigger = "new_session"',
        "message_hash_fallback = true",
        "",
        "# Start cheap, escalate when the weak model shows signs of stalling.",
        "[routes.stage]",
        f'id = "{ROUTE_STAGE}"',
        'type = "stage_router"',
        f'capable_target = "{_key(strong.id)}"',
        f'efficient_target = "{_key(weak.id)}"',
        'picker = "efficient_first"',
        "confidence_threshold = 0.5",
        "recent_turn_window = 3",
        "",
    ]
    return "\n".join(lines)


def write(cfg: TurnoutConfig, turnout_base_url: str | None = None) -> Path:
    out = cfg.resolve(cfg.switchyard.config_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(generate(cfg, turnout_base_url))
    return out
